server:
  port: 8765
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      locator:
        enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
          - Path=/account/**
          filters:
          - RewritePath=/account/(?<path>.*), /$\{path}
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
          - Path=/transaction/**
          filters:
          - RewritePath=/transaction/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}