 using hostname.

[code language="java"]
node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/arinsinc/factorial.git', credentialsId: 'arinsinc', branch: 'main'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('config-service') {
                def app = docker.build "localhost:5000/config-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/config-service:${env.version}").run('-p 2222:2222 -h config --name config --link discovery --link account --link gateway --link transaction')
        }

        stage ('Final') {
            build job: 'config-service-pipeline', wait: false
        }

    }

}