spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
        default_schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/factorial_development
    username: postgres
    password: admin
    initialization-mode: always
    initialize: true
    continue-on-error: true
  security:
    basic:
      enabled: false